# Generated by Django 3.2 on 2023-05-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('text', models.TextField()),
                ('image', models.ImageField(upload_to='post/%Y/%m/%d')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('like', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
