# Generated by Django 3.2 on 2023-05-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_rename_category_post_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post/%Y/%m/%d', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Контент'),
        ),
    ]
